export enum Services {
  USER = 'USER_SERVICE',
  AUTH = 'AUTH_SERVICE',
  APPOINTMENT = 'APPOINTMENT_SERVICE',
  RESULT = 'RESULT_SERVICE',
  SCHEDULE = 'SCHEDULE_SERVICE',
}

export enum Repository {
  USER = 'USER_REPOSITORY',
  APPOINTMENT = 'APPOINMENT_REPOSITORY',
  RESULT = 'RESULT_REPOSITORY',
  SCHEDULE = 'SCHEDULE_REPOSITORY',
}
